- defaults:
    link:
      create: true
      relink: true
      force: true

- clean: ["~", "~/.config", "~/.config/fish"]

- create:
    ~/.local/bin:
      mode: 0755

- link:
    ~/.gpg.conf:
    ~/.gitconfig:
    ~/.gitignore_global:
    ~/.config/fish: fish
    ~/.config/starship.toml: starship.toml

- shell:
    - description: Initializing submodules
      command: git submodule update --init --recursive
    - description: Updating submodules
      command: git submodule update --remote --recursive
    - description: Installing Starship
      command: ./starship/install/install.sh --yes --bin-dir ~/.local/bin
