- defaults:
    link:
      create: true
      relink: true
      force: true

- clean: ["~", "~/.config", "~/.antigen"]

- link:
    ~/.antigen/antigen: antigen
    ~/.antigenrc:
    ~/.fzf:
    ~/.gitconfig:
    ~/.gitignore_global:
    ~/.gpg.conf:
    ~/.hidden:
    ~/.config/starship.toml: starship.toml
    ~/.zshrc:

- shell:
    - description: Initializing submodules
      command: git submodule update --init --recursive
    - description: Updating submodules
      command: git submodule update --remote --recursive
    - description: Installing FZF
      command: ./fzf/install --no-bash --no-fish --key-bindings --completion --no-update-rc
    - description: Installing Starship
      command: ./starship/install/install.sh --yes --bin-dir ~/bin
