- defaults:
    link:
      create: true
      relink: true

- clean: ['~']

- link:
    ~/.antigen/antigen: antigen
    ~/.antigenrc:
    ~/.gitconfig:
    ~/.zshrc:

- shell:
    - [git submodule update --init --recursive, Installing submodules]
