- defaults:
    link:
      create: true
      relink: true
      force: true

- clean: ['~', '~/.config', '~/.antigen']

- link:
    ~/.antigen/antigen: antigen
    ~/.antigenrc:
    ~/.fzf:
    ~/.gitconfig:
    ~/.gpg.conf:
    ~/.hidden:
    ~/.zshrc:

- shell:
    -
      description: Initializing submodules
      command: git submodule update --init --recursive
    -
      description: Installing FZF
      command: ./fzf/install --no-bash --no-fish --key-bindings --completion --no-update-rc