- defaults:
    link:
      create: true
      relink: true
      force: true

- clean: ["~", "~/.config", "~/.config/fish"]

- create:
    ~/.local/bin:
      mode: 0755

- link:
    ~/.gpg.conf: home/gpg.conf
    ~/.gitconfig: home/gitconfig
    ~/.fzfignore: home/fzfignore
    ~/.config/fish: home/config/fish
    ~/.config/starship.toml: home/config/starship.toml

- shell:
    - description: Initializing submodules
      command: git submodule update --init --recursive
    - description: Updating submodules
      command: git submodule update --remote --recursive
    - description: Installing Starship
      command: curl -fsSL https://starship.rs/install.sh | sh -s -- --yes --bin-dir ~/.local/bin
    - description: Installing Fast Node Manager (FNM)
      command: curl -fsSL https://fnm.vercel.app/install | sh -s -- --skip-shell
    - description: Installing Rustup
      command: curl -fsSL https://sh.rustup.rs | sh -s -- -y --no-modify-path
